import React, { createContext, useContext, useState, useEffect } from 'react';
export const languages = {
    en: {
        name: "English",
        flag: "🇺🇸",
        nativeName: "English"
    },
    hi: {
        name: "Hindi",
        flag: "🇮🇳",
        nativeName: "हिंदी"
    },
    gu: {
        name: "Gujarati",
        flag: "🇮🇳",
        nativeName: "ગુજરાતી"
    }
};
export const translations = {
    en: {
        // Common
        login: "Login",
        register: "Register",
        logout: "Logout",
        dashboard: "Dashboard",
        profile: "Profile",
        settings: "Settings",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
        view: "View",
        back: "Back",
        loading: "Loading...",
        // Navigation
        home: "Home",
        marketplace: "Marketplace",
        orders: "Orders",
        inventory: "Inventory",
        // Dashboard
        welcomeBack: "Welcome back",
        findSuppliers: "Find Suppliers",
        myOrders: "My Orders",
        activeOrders: "Active Orders",
        inTransit: "In Transit",
        savedItems: "Saved Items",
        totalProducts: "Total Products",
        pendingOrders: "Pending Orders",
        monthlyRevenue: "Monthly Revenue",
        completedOrders: "Completed Orders",
        // Actions
        addToCart: "Add to Cart",
        viewDetails: "View Details",
        contactSupplier: "Contact Supplier",
        trackOrder: "Track Order",
        makePayment: "Make Payment",
        // Marketplace
        vendorMarketplace: "Vendor Marketplace",
        vendorMarketplaceSubtitle: "Buy and sell unused items with other vendors",
        searchItems: "Search for items...",
        category: "Category",
        allCategories: "All Categories",
        spices: "Spices",
        oils: "Oils & Fats",
        grains: "Grains",
        equipment: "Equipment",
        packaging: "Packaging",
        sortBy: "Sort by",
        mostRecent: "Most Recent",
        priceLowToHigh: "Price: Low to High",
        priceHighToLow: "Price: High to Low",
        byCondition: "By Condition",
        contactSeller: "Contact Seller",
        urgentSale: "Urgent Sale",
        addedToWishlist: "Added to Wishlist",
        itemSavedToWishlist: "Item saved to your wishlist",
        backToDashboard: "Back to Dashboard",
        noItemsFound: "No items found",
        tryAdjustingFilters: "Try adjusting your search or filters",
        // Sell Items Form
        sellItems: "Sell Items",
        listYourItems: "List Your Items",
        sellUnusedItemsToOtherVendors: "Sell unused items to other vendors in our marketplace",
        basicInformation: "Basic Information",
        provideEssentialDetails: "Provide essential details about your item",
        itemTitle: "Item Title",
        itemTitlePlaceholder: "e.g., Commercial Rice Cooker - Barely Used",
        selectCategory: "Select category",
        condition: "Condition",
        selectCondition: "Select condition",
        description: "Description",
        descriptionPlaceholder: "Describe your item, its condition, why you're selling, etc.",
        pricing: "Pricing",
        setCompetitivePrices: "Set competitive prices to attract buyers",
        sellingPrice: "Selling Price",
        originalPrice: "Original Price",
        greatDeal: "Great deal! Buyers save",
        photos: "Photos",
        addPhotosToShowcase: "Add photos to showcase your item (up to 5 images)",
        addPhoto: "Add Photo",
        preview: "Preview",
        additionalOptions: "Additional Options",
        urgency: "Urgency",
        normalSale: "Normal Sale",
        tags: "Tags",
        commaSeparated: "comma separated",
        tagsPlaceholder: "commercial, bulk, sealed, etc.",
        listItemForSale: "List Item for Sale",
        listingGuidelines: "Listing Guidelines",
        beHonestAboutCondition: "Be honest about item condition",
        includeClearPhotos: "Include clear, well-lit photos",
        respondPromptly: "Respond to inquiries promptly",
        priceCompetitively: "Price competitively",
        missingInformation: "Missing Information",
        fillRequiredFields: "Please fill in all required fields",
        itemListedSuccessfully: "Item Listed Successfully!",
        postedToMarketplace: "has been posted to the vendor marketplace",
        // Payment
        completePayment: "Complete Payment",
        securePayment: "Secure Payment",
        securePaymentDescription: "Your payment is protected by 256-bit SSL encryption",
        paymentDetails: "Payment Details",
        orderSummary: "Order Summary",
        cardNumber: "Card Number",
        expiryDate: "Expiry Date",
        cvc: "CVC",
        cardholderName: "Cardholder Name",
        cardholderNamePlaceholder: "Name as it appears on card",
        paymentSecurityNotice: "Your payment information is encrypted and secure",
        processingPayment: "Processing Payment",
        pleaseWait: "Please wait while we process your payment...",
        paymentSuccessful: "Payment Successful!",
        orderBeingPrepared: "Your order is being prepared",
        paymentFailed: "Payment Failed",
        paymentErrorMessage: "There was an error processing your payment. Please try again.",
        orderConfirmed: "Your order has been confirmed",
        payAmount: "Pay {amount}",
        andMoreItems: "and {count} more items",
        total: "Total",
        // Cart
        shoppingCart: "Shopping Cart",
        cartEmpty: "Your cart is empty",
        cartEmptyDescription: "Looks like you haven't added any items to your cart yet",
        continueShopping: "Continue Shopping",
        reviewItemsAndProceed: "Review your items and proceed to checkout",
        items: "items",
        deliveryPreference: "Delivery Preference",
        expressDelivery: "Express Delivery",
        standardDelivery: "Standard Delivery",
        economyDelivery: "Economy Delivery",
        deliveryExpress: "2-4 hours",
        deliveryStandard: "Same day",
        deliveryEconomy: "1-2 days",
        deliveryFee: "Delivery fee",
        urgency: "Urgency",
        normalUrgency: "Normal",
        urgentRequest: "Urgent Request",
        specialInstructions: "Special Instructions",
        specialInstructionsPlaceholder: "Any special instructions for the supplier...",
        subtotal: "Subtotal",
        deliveryInformation: "Delivery Information",
        deliveryAddress: "Delivery Address",
        deliveryAddressPlaceholder: "Enter your complete delivery address...",
        phoneNumber: "Phone Number",
        phoneNumberPlaceholder: "+91 98765 43210",
        deliveryFees: "Delivery Fees",
        proceedToPayment: "Proceed to Payment",
        secureCheckoutNotice: "Secure checkout powered by SSL encryption",
        missingInformation: "Missing Information",
        provideAddressAndPhone: "Please provide delivery address and phone number",
        emptyCart: "Empty Cart",
        addItemsBeforeCheckout: "Please add items to your cart before checkout",
        orderPlacedSuccessfully: "Order Placed Successfully!",
        orderWorth: "Order worth",
        placedWithSuppliers: "has been placed with {count} supplier(s)",
        // Order Tracking
        liveTracking: "Live Tracking",
        trackingOrder: "Tracking Order",
        liveLocationUpdates: "Live location updates every 5 seconds",
        outForDelivery: "Out for Delivery",
        backToOrders: "Back to Orders",
        liveMap: "Live Map View",
        driverLocation: "Driver Location",
        estimatedArrival: "Estimated arrival",
        away: "away",
        yourDriver: "Your Driver",
        deliveries: "deliveries",
        call: "Call",
        message: "Message",
        orderDetails: "Order Details",
        deliveryProgress: "Delivery Progress",
        quickActions: "Quick Actions",
        callDriver: "Call Driver",
        reorderItems: "Reorder Items",
        reportIssue: "Report Issue",
        callingDriver: "Calling Driver",
        calling: "Calling",
        // WhatsApp Integration
        whatsApp: "WhatsApp",
        chooseMessageTemplate: "Choose a message template to contact",
        verified: "Verified",
        quickTemplates: "Quick Templates",
        productInquiry: "Product Inquiry",
        askAboutAvailabilityAndDelivery: "Ask about availability and delivery",
        bulkOrder: "Bulk Order",
        inquireAboutBulkPricing: "Inquire about bulk pricing",
        urgentRequirement: "Urgent Requirement",
        needImmediateDelivery: "Need immediate delivery",
        qualityInquiry: "Quality Inquiry",
        askAboutQualitySpecs: "Ask about quality specifications",
        generalInquiry: "General Inquiry",
        askForCatalogAndPricing: "Ask for catalog and pricing",
        customMessage: "Custom Message",
        optional: "optional",
        customMessagePlaceholder: "Type your own message...",
        sendMessage: "Send Message",
        invalidPhoneNumber: "Invalid Phone Number",
        pleaseCheckPhoneNumber: "Please check the phone number and try again",
        openingWhatsApp: "Opening WhatsApp",
        startingChatWith: "Starting chat with",
        // Rating and Reviews
        vendorRatingsAndReviews: "Vendor Ratings & Reviews",
        overallRating: "Overall rating",
        basedOnReviews: "Based on {count} reviews",
        writeReview: "Write Review",
        writeYourReview: "Write Your Review",
        shareYourExperience: "Share your experience with other vendors",
        yourRating: "Your Rating",
        yourComment: "Your Comment",
        shareDetailedFeedback: "Share your detailed feedback about the service, quality, delivery, etc.",
        submitReview: "Submit Review",
        customerReviews: "Customer Reviews",
        order: "Order",
        helpful: "Helpful",
        close: "Close",
        pleaseProvideRating: "Please Provide Rating",
        ratingRequired: "Please provide a rating before submitting",
        reviewSubmitted: "Review Submitted",
        thankYouForReview: "Thank you for your feedback!",
        // Messages
        loginSuccess: "Login successful",
        profileUpdated: "Profile updated successfully",
        itemAdded: "Item added to cart"
    },
    hi: {
        // Common
        login: "लॉगिन",
        register: "पंजीकरण",
        logout: "लॉगआउट",
        dashboard: "डैशबोर्ड",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        save: "सेव करें",
        cancel: "���द्द करें",
        edit: "संपादित करें",
        delete: "हटाएं",
        view: "देखें",
        back: "वापस",
        loading: "लोड हो रहा है...",
        // Navigation
        home: "होम",
        marketplace: "मार्केटप्लेस",
        orders: "ऑर्डर",
        inventory: "इन्वेंट्री",
        // Dashboard
        welcomeBack: "वापसी पर स्वागत है",
        findSuppliers: "आपूर्तिकर्ता खोजें",
        myOrders: "मेरे ऑर्डर",
        activeOrders: "सक्रिय ऑर्डर",
        inTransit: "ट्रांजिट में",
        savedItems: "सेव किए गए आइटम",
        totalProducts: "कुल उत्पाद",
        pendingOrders: "लंबित ऑर्डर",
        monthlyRevenue: "मासिक आय",
        completedOrders: "पूर्ण ऑर्डर",
        // Actions
        addToCart: "कार्ट में जोड़ें",
        viewDetails: "विवरण देखें",
        contactSupplier: "आपूर्तिकर्ता से संपर्क करें",
        trackOrder: "ऑर्डर ट्रैक करें",
        makePayment: "भुगतान करें",
        // Marketplace
        vendorMarketplace: "विक्रेता बाज़ार",
        vendorMarketplaceSubtitle: "अन्य विक्रेताओं के साथ अनुपयोगी वस्तुओं को खरीदें और ���ेचें",
        searchItems: "वस्तुओं की खोज करें...",
        category: "श्रेणी",
        allCategories: "सभी श्रेणियां",
        spices: "मसाले",
        oils: "तेल और वसा",
        grains: "अनाज",
        equipment: "उपकरण",
        packaging: "पैकेजिंग",
        sortBy: "क्रमबद्ध करें",
        mostRecent: "सबसे हाल का",
        priceLowToHigh: "मूल्य: कम से अधिक",
        priceHighToLow: "मूल्य: अधिक से कम",
        byCondition: "स्थिति के अनुसार",
        contactSeller: "विक्रेता से संपर्क करें",
        urgentSale: "तत्काल बिक्री",
        addedToWishlist: "इच्छा सूची में जोड़ा गया",
        itemSavedToWishlist: "आइटम आपकी ���च्छा सूची में सेव किया गया",
        backToDashboard: "डैशबोर्ड पर वापस जाएं",
        noItemsFound: "कोई आइटम नहीं मिला",
        tryAdjustingFilters: "अपनी खोज या फ़िल्टर को समायोजित ���रने का प्रयास करें",
        // Messages
        loginSuccess: "लॉगिन सफल",
        profileUpdated: "प्रोफाइ��� सफलतापूर्वक अपडेट किया गया",
        itemAdded: "आइटम कार्ट में जोड़ा गया"
    },
    gu: {
        // Common
        login: "લૉગિન",
        register: "નોંધણી",
        logout: "લૉગઆઉટ",
        dashboard: "ડેશબોર્ડ",
        profile: "પ્રોફાઈલ",
        settings: "સેટિંગ્સ",
        save: "સેવ કરો",
        cancel: "રદ કરો",
        edit: "એડિટ કરો",
        delete: "ડિલીટ કરો",
        view: "જુઓ",
        back: "પાછા",
        loading: "લોડ થઈ રહ્યું છે...",
        // Navigation
        home: "હોમ",
        marketplace: "માર્કેટપ્લેસ",
        orders: "ઓર્ડર",
        inventory: "ઇન્વેન્ટરી",
        // Dashboard
        welcomeBack: "પાછા આવવા બદલ સ્વાગત",
        findSuppliers: "સપ્લાયર શોધો",
        myOrders: "મારા ઓર્ડર",
        activeOrders: "એક્ટિવ ઓર���ડર",
        inTransit: "ટ્રાન્ઝિટમાં",
        savedItems: "સેવ કરેલા આઇટમ",
        totalProducts: "કુલ પ્ર��ડક્ટ",
        pendingOrders: "પેન્ડિંગ ઓર્ડર",
        monthlyRevenue: "માસિક આવક",
        completedOrders: "પૂર્ણ ઓર્ડર",
        // Actions
        addToCart: "કાર્ટમાં ઉમેરો",
        viewDetails: "વિગતો જુઓ",
        contactSupplier: "સપ્લાયર સાથે સંપર્ક કરો",
        trackOrder: "ઓર્ડર ટ્રેક કરો",
        makePayment: "પેમેન્ટ કરો",
        // Marketplace
        vendorMarketplace: "વેન્ડર માર્કેટપ્લેસ",
        vendorMarketplaceSubtitle: "અન્ય વેન્ડર સાથે વણઉપયોગી વસ્તુઓ ખરીદો અને વેચો",
        searchItems: "વસ્તુઓ શોધો...",
        category: "કેટેગરી",
        allCategories: "બધી કેટેગરી",
        spices: "મસાલા",
        oils: "તેલ અને ચરબી",
        grains: "અનાજ",
        equipment: "સાધનો",
        packaging: "પેકેજિંગ",
        sortBy: "ક્રમમાં ગોઠવો",
        mostRecent: "સૌથી તાજેતરનું",
        priceLowToHigh: "કિંમત: ઓછીથી વધુ",
        priceHighToLow: "કિંમત: વધુથી ઓછી",
        byCondition: "સ્થિતિ પ્રમાણે",
        contactSeller: "વેચનાર સાથે સંપર્ક કરો",
        urgentSale: "તાત્કાલિક વેચાણ",
        addedToWishlist: "વિશલિસ્ટમાં ઉમેરાયું",
        itemSavedToWishlist: "આઇટમ તમારી વિશલિસ્ટમાં સેવ થયું",
        backToDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
        noItemsFound: "કોઈ આઇટમ મળ્યું નથી",
        tryAdjustingFilters: "તમારી શોધ અથવા ફિલ્ટર સમાયોજિત કરવાનો પ્રયાસ કરો",
        // Messages
        loginSuccess: "લૉગિન સફળ",
        profileUpdated: "પ્રોફાઈલ સફળતાપૂર્વક અપડેટ થયું",
        itemAdded: "આઇટમ કાર્ટમાં ઉમેરાયું"
    }
};
const LanguageContext = /*#__PURE__*/ createContext(undefined);
export const useLanguage = ()=>{
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
export const LanguageProvider = ({ children })=>{
    const [language, setLanguageState] = useState('en');
    useEffect(()=>{
        const savedLanguage = localStorage.getItem('preferred_language');
        if (savedLanguage && languages[savedLanguage]) {
            setLanguageState(savedLanguage);
        }
    }, []);
    const setLanguage = (lang)=>{
        setLanguageState(lang);
        localStorage.setItem('preferred_language', lang);
    };
    const t = (key)=>{
        return translations[language]?.[key] || translations.en[key] || key;
    };
    return /*#__PURE__*/ React.createElement(LanguageContext.Provider, {
        value: {
            language,
            setLanguage,
            t
        }
    }, children);
};
