import User from "../models/User.js";
import Material from "../models/Material.js";

const DEMO_VENDOR = {
  name: "Rajesh Kumar",
  email: "vendor@example.com",
  password: "vendor123",
  phone: "+91 98765 43210",
  role: "vendor",
  businessName: "Rajesh's Chaat Corner",
  address: "Sector 15, Noida, Uttar Pradesh",
  description: "Serving delicious North Indian street food since 2015",
  specialties: ["Chaat", "Pani Puri", "Dahi Bhalla"],
  isVerified: true,
  emailVerified: true,
  location: { type: "Point", coordinates: [77.391, 28.5355] },
};

const DEMO_VENDOR_2 = {
  name: "Sunita Devi",
  email: "vendor2@example.com",
  password: "vendor123",
  phone: "+91 91234 56789",
  role: "vendor",
  businessName: "Sunita's South Indian Kitchen",
  address: "Karol Bagh, New Delhi",
  description: "Authentic South Indian street food — dosa, idli, vada and more",
  specialties: ["Dosa", "Idli", "Sambar", "Vada"],
  isVerified: true,
  emailVerified: true,
  location: { type: "Point", coordinates: [77.19, 28.65] },
};

const DEMO_SUPPLIER = {
  name: "Priya Sharma",
  email: "supplier@example.com",
  password: "supplier123",
  phone: "+91 99887 66554",
  role: "supplier",
  businessName: "Priya Raw Materials Supply",
  address: "Industrial Area, Sector 62, Noida, Uttar Pradesh",
  description: "Leading supplier of premium quality oils, spices and grains for the food industry. Serving Delhi NCR since 1998 with authentic and pure products.",
  categories: ["Spices", "Oil", "Grains", "Pulses", "Dairy", "Vegetables", "Flours", "Sweeteners"],
  deliveryAreas: ["Delhi", "Noida", "Gurgaon", "Faridabad", "Greater Noida", "Ghaziabad", "Meerut"],
  businessType: "Wholesale Distributor",
  license: "FSSAI-12345678901234",
  gstNumber: "09AABCU9603R1ZX",
  panNumber: "AABCU9603R",
  fssaiLicense: "FSSAI-12345678901234",
  establishedYear: "1998",
  deliveryFee: 50,
  freeDeliveryAbove: 1000,
  minOrderAmount: 500,
  maxDeliveryDistance: 25,
  estimatedDeliveryTime: "2-4 hours",
  acceptingOrders: true,
  isVerified: true,
  emailVerified: true,
  rating: 4.8,
  totalRatings: 186,
  totalOrders: 186,
  totalRevenue: 720000,
  location: { type: "Point", coordinates: [77.4538, 28.6692] },
};

const DEMO_SUPPLIER_2 = {
  name: "Arjun Mehta",
  email: "supplier2@example.com",
  password: "supplier123",
  phone: "+91 88776 55443",
  role: "supplier",
  businessName: "Mehta Fresh Farms & Supplies",
  address: "Azadpur Mandi, New Delhi",
  description: "Fresh farm produce, vegetables and dairy delivered daily. Sourced directly from farms in Haryana and UP.",
  categories: ["Vegetables", "Dairy", "Fresh Produce", "Herbs"],
  deliveryAreas: ["Delhi", "Noida", "Gurgaon", "Rohini", "Dwarka"],
  businessType: "Direct Manufacturer",
  license: "FSSAI-98765432109876",
  gstNumber: "07AABCM1234R1ZP",
  panNumber: "AABCM1234R",
  fssaiLicense: "FSSAI-98765432109876",
  establishedYear: "2005",
  deliveryFee: 30,
  freeDeliveryAbove: 800,
  minOrderAmount: 300,
  maxDeliveryDistance: 30,
  estimatedDeliveryTime: "1-2 hours",
  acceptingOrders: true,
  isVerified: true,
  emailVerified: true,
  rating: 4.6,
  totalRatings: 94,
  totalOrders: 94,
  totalRevenue: 310000,
  location: { type: "Point", coordinates: [77.17, 28.72] },
};

const DEMO_MATERIALS = [
  // ── OILS ──────────────────────────────────────────────
  {
    name: "Premium Mustard Oil",
    category: "Oil",
    price: 180,
    unit: "litre",
    stock: 200,
    description: "Cold-pressed pure mustard oil with characteristic pungency. Perfect for pickles, stir-fries and authentic Indian cooking.",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    tags: ["oil", "mustard", "cooking", "premium", "cold-pressed"],
    minOrderQuantity: 5,
    maxOrderQuantity: 100,
    storageInstructions: "Store in a cool, dry place away from sunlight",
    shelfLife: "12 months",
    origin: "Rajasthan",
    certifications: ["FSSAI", "ISO 9001"],
    isActive: true,
  },
  {
    name: "Refined Sunflower Oil",
    category: "Oil",
    price: 145,
    unit: "litre",
    stock: 300,
    description: "Light, refined sunflower oil with high smoke point. Ideal for deep frying samosas, pakoras and puris.",
    image: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400",
    tags: ["oil", "sunflower", "refined", "frying"],
    minOrderQuantity: 5,
    maxOrderQuantity: 150,
    shelfLife: "12 months",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Pure Groundnut Oil",
    category: "Oil",
    price: 195,
    unit: "litre",
    stock: 180,
    description: "Wood-pressed peanut oil with rich nutty flavour. Widely used in South Indian and Gujarati cuisine.",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    tags: ["oil", "groundnut", "peanut", "wood-pressed"],
    minOrderQuantity: 5,
    maxOrderQuantity: 100,
    shelfLife: "9 months",
    origin: "Gujarat",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Pure Desi Ghee",
    category: "Dairy",
    price: 560,
    unit: "kg",
    stock: 100,
    description: "Traditional cow ghee made from cultured butter. Rich aroma, golden colour and perfect for halwa, dal tadka and rotis.",
    image: "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=400",
    tags: ["ghee", "dairy", "cow", "traditional", "desi"],
    minOrderQuantity: 2,
    maxOrderQuantity: 50,
    shelfLife: "12 months",
    origin: "Haryana",
    certifications: ["FSSAI", "Agmark"],
    isActive: true,
  },
  {
    name: "Refined Coconut Oil",
    category: "Oil",
    price: 220,
    unit: "litre",
    stock: 120,
    description: "Pure refined coconut oil ideal for South Indian cooking — dosas, curries and chutneys.",
    image: "https://images.unsplash.com/photo-1556909211-36987daf7b4d?w=400",
    tags: ["oil", "coconut", "south-indian"],
    minOrderQuantity: 5,
    maxOrderQuantity: 80,
    shelfLife: "24 months",
    origin: "Kerala",
    certifications: ["FSSAI"],
    isActive: true,
  },

  // ── SPICES ────────────────────────────────────────────
  {
    name: "Garam Masala (House Blend)",
    category: "Spices",
    price: 320,
    unit: "kg",
    stock: 80,
    description: "12-spice house-blended garam masala with cardamom, cinnamon, cloves, bay leaf and more.",
    image: "https://images.unsplash.com/photo-1599909533734-cb5180b78a3a?w=400",
    tags: ["spices", "masala", "garam", "blend"],
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    shelfLife: "12 months",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Red Chilli Powder (Kashmiri)",
    category: "Spices",
    price: 280,
    unit: "kg",
    stock: 120,
    description: "Vibrant Kashmiri red chilli powder — bright colour, mild heat. Perfect for tandoori dishes and gravies.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    tags: ["spices", "chilli", "kashmiri", "red"],
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    shelfLife: "12 months",
    origin: "Kashmir",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Turmeric Powder (Rajapuri)",
    category: "Spices",
    price: 160,
    unit: "kg",
    stock: 200,
    description: "High-curcumin Rajapuri turmeric powder. Deep golden colour, earthy aroma and anti-inflammatory properties.",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400",
    tags: ["spices", "turmeric", "haldi", "organic"],
    minOrderQuantity: 2,
    maxOrderQuantity: 100,
    shelfLife: "24 months",
    origin: "Maharashtra",
    certifications: ["FSSAI", "Organic India"],
    isActive: true,
  },
  {
    name: "Coriander-Cumin Powder (Dhana-Jeeru)",
    category: "Spices",
    price: 210,
    unit: "kg",
    stock: 150,
    description: "Perfectly balanced 60:40 coriander-cumin blend, stone-ground for maximum freshness.",
    image: "https://images.unsplash.com/photo-1599909533734-cb5180b78a3a?w=400",
    tags: ["spices", "coriander", "cumin", "dhana", "jeeru"],
    minOrderQuantity: 2,
    maxOrderQuantity: 80,
    shelfLife: "12 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Chaat Masala",
    category: "Spices",
    price: 350,
    unit: "kg",
    stock: 90,
    description: "Tangy chaat masala with amchur, black salt, cumin and mint. Essential for pani puri, bhel puri and fruit chaat.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    tags: ["spices", "chaat", "masala", "tangy"],
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    shelfLife: "12 months",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Panch Phoron (Bengali Five-Spice)",
    category: "Spices",
    price: 240,
    unit: "kg",
    stock: 60,
    description: "Whole spice blend of fenugreek, nigella, cumin, mustard and fennel seeds used in Bengali & Odia cuisine.",
    image: "https://images.unsplash.com/photo-1599909533734-cb5180b78a3a?w=400",
    tags: ["spices", "panch", "phoron", "bengali", "whole-spice"],
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
    shelfLife: "18 months",
    origin: "West Bengal",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Dried Mango Powder (Amchur)",
    category: "Spices",
    price: 190,
    unit: "kg",
    stock: 100,
    description: "Raw mango sun-dried and powdered. Adds tartness to chaat, samosa filling, dal and chutneys.",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400",
    tags: ["spices", "amchur", "mango", "sour", "chaat"],
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    shelfLife: "12 months",
    origin: "Uttar Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Cumin Seeds (Jeera)",
    category: "Spices",
    price: 300,
    unit: "kg",
    stock: 140,
    description: "Whole cumin seeds from Rajasthan — aromatic, earthy and essential for tadka in dals and curries.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    tags: ["spices", "cumin", "jeera", "whole"],
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    shelfLife: "18 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },

  // ── GRAINS & FLOURS ───────────────────────────────────
  {
    name: "Basmati Rice (Premium Long Grain)",
    category: "Grains",
    price: 120,
    unit: "kg",
    stock: 500,
    description: "Aged premium long-grain basmati rice — fragrant, fluffy and perfect for biryani and pulao.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    tags: ["rice", "basmati", "grains", "biryani"],
    minOrderQuantity: 10,
    maxOrderQuantity: 500,
    shelfLife: "24 months",
    origin: "Dehradun",
    certifications: ["FSSAI", "Agmark"],
    isActive: true,
  },
  {
    name: "Sona Masoori Rice",
    category: "Grains",
    price: 75,
    unit: "kg",
    stock: 400,
    description: "Light, low-starch Sona Masoori rice ideal for idli, dosa batter and everyday South Indian meals.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    tags: ["rice", "sona-masoori", "south-indian", "idli", "dosa"],
    minOrderQuantity: 10,
    maxOrderQuantity: 300,
    shelfLife: "18 months",
    origin: "Andhra Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Whole Wheat Atta (Stone Ground)",
    category: "Grains",
    price: 45,
    unit: "kg",
    stock: 600,
    description: "Traditional chakki-ground whole wheat flour — perfect for soft rotis, parathas and puris.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    tags: ["atta", "wheat", "flour", "roti", "paratha"],
    minOrderQuantity: 10,
    maxOrderQuantity: 500,
    shelfLife: "3 months",
    origin: "Punjab",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Besan (Gram Flour)",
    category: "Grains",
    price: 65,
    unit: "kg",
    stock: 350,
    description: "Finely milled chickpea flour — key ingredient for pakoras, kadhi, besan chilla and sweets like mysore pak.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    tags: ["besan", "gram-flour", "chickpea", "pakora", "kadhi"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "6 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Rice Flour (Fine)",
    category: "Grains",
    price: 55,
    unit: "kg",
    stock: 250,
    description: "Finely ground rice flour for making appam, rice rotis, murukku and crispy coatings.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    tags: ["rice-flour", "appam", "murukku", "south-indian"],
    minOrderQuantity: 5,
    maxOrderQuantity: 150,
    shelfLife: "6 months",
    origin: "Tamil Nadu",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Suji / Rava (Semolina)",
    category: "Grains",
    price: 50,
    unit: "kg",
    stock: 300,
    description: "Coarse-ground semolina for upma, halwa, rava dosa, idli and crispy coatings.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    tags: ["suji", "rava", "semolina", "upma", "halwa"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "6 months",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Maize Flour (Makki Atta)",
    category: "Grains",
    price: 35,
    unit: "kg",
    stock: 280,
    description: "Coarse ground corn flour for making makki ki roti, dhokla and Punjabi winter classics.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    tags: ["makki", "maize", "corn-flour", "punjabi"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "4 months",
    origin: "Punjab",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Poha (Flattened Rice)",
    category: "Grains",
    price: 60,
    unit: "kg",
    stock: 200,
    description: "Thick-cut flattened rice flakes ideal for poha breakfast, chivda snack mix and kanda poha.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    tags: ["poha", "flattened-rice", "breakfast", "chivda"],
    minOrderQuantity: 5,
    maxOrderQuantity: 100,
    shelfLife: "6 months",
    origin: "Madhya Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },

  // ── PULSES & LENTILS ─────────────────────────────────
  {
    name: "Toor Dal (Yellow Pigeon Pea)",
    category: "Pulses",
    price: 140,
    unit: "kg",
    stock: 350,
    description: "Unpolished toor dal rich in protein. Perfect for everyday sambar, dal fry and dal tadka.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["dal", "toor", "pigeon-pea", "pulses", "sambar"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "12 months",
    origin: "Maharashtra",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Moong Dal (Split Green Gram)",
    category: "Pulses",
    price: 130,
    unit: "kg",
    stock: 280,
    description: "Husked and split green moong dal — easy to digest, quick to cook. Used in dal, khichdi and cheelas.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["dal", "moong", "green-gram", "pulses", "khichdi"],
    minOrderQuantity: 5,
    maxOrderQuantity: 150,
    shelfLife: "12 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Chana Dal (Split Bengal Gram)",
    category: "Pulses",
    price: 110,
    unit: "kg",
    stock: 320,
    description: "Split chana dal with nutty flavour — used for dal, chana masala, halwa and as a tadka ingredient.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["dal", "chana", "bengal-gram", "pulses"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "18 months",
    origin: "Madhya Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Masoor Dal (Red Lentil)",
    category: "Pulses",
    price: 120,
    unit: "kg",
    stock: 250,
    description: "Quick-cooking red lentils with earthy flavour. Perfect for everyday dal, soups and khichdi.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["dal", "masoor", "red-lentil", "pulses"],
    minOrderQuantity: 5,
    maxOrderQuantity: 150,
    shelfLife: "18 months",
    origin: "Uttar Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Kabuli Chana (White Chickpea)",
    category: "Pulses",
    price: 125,
    unit: "kg",
    stock: 300,
    description: "Large white chickpeas for making chole bhature, hummus, chana masala and sundal.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["chana", "chickpea", "chole", "bhature", "pulses"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "24 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Urad Dal (Black Gram Skinned)",
    category: "Pulses",
    price: 145,
    unit: "kg",
    stock: 220,
    description: "Skinned urad dal with creamy texture when cooked. Essential for idli-dosa batter, makhani dal and vada.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["dal", "urad", "black-gram", "idli", "dosa", "vada"],
    minOrderQuantity: 5,
    maxOrderQuantity: 150,
    shelfLife: "18 months",
    origin: "Andhra Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Rajma (Red Kidney Beans)",
    category: "Pulses",
    price: 150,
    unit: "kg",
    stock: 200,
    description: "Dark red kidney beans from Jammu hills — meaty, flavourful and great for rajma-chawal.",
    image: "https://images.unsplash.com/photo-1604908554002-c45d2b40d1d4?w=400",
    tags: ["rajma", "kidney-beans", "pulses", "punjabi"],
    minOrderQuantity: 5,
    maxOrderQuantity: 100,
    shelfLife: "24 months",
    origin: "Himachal Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },

  // ── DAIRY & EGGS ─────────────────────────────────────
  {
    name: "Fresh Paneer (Cottage Cheese)",
    category: "Dairy",
    price: 340,
    unit: "kg",
    stock: 80,
    description: "Freshly made full-fat paneer with soft texture. Ideal for paneer tikka, matar paneer and paneer bhurji.",
    image: "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=400",
    tags: ["paneer", "dairy", "cheese", "tikka", "fresh"],
    minOrderQuantity: 2,
    maxOrderQuantity: 30,
    shelfLife: "5 days",
    origin: "Delhi NCR",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Curd / Dahi (Full Fat)",
    category: "Dairy",
    price: 60,
    unit: "kg",
    stock: 150,
    description: "Set curd made from full-fat buffalo milk. Essential for dahi bhalla, raita, lassi and marinades.",
    image: "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=400",
    tags: ["curd", "dahi", "yogurt", "dairy", "raita"],
    minOrderQuantity: 5,
    maxOrderQuantity: 50,
    shelfLife: "3 days",
    origin: "Haryana",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Buttermilk (Chaas) Concentrate",
    category: "Dairy",
    price: 40,
    unit: "litre",
    stock: 100,
    description: "Tangy churned buttermilk concentrate. Just dilute with water for refreshing chaas and kadhi base.",
    image: "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=400",
    tags: ["chaas", "buttermilk", "kadhi", "dairy"],
    minOrderQuantity: 5,
    maxOrderQuantity: 50,
    shelfLife: "5 days",
    certifications: ["FSSAI"],
    isActive: true,
  },

  // ── VEGETABLES & FRESH PRODUCE ────────────────────────
  {
    name: "Onions (Grade A)",
    category: "Vegetables",
    price: 28,
    unit: "kg",
    stock: 800,
    description: "Fresh red onions from Nashik — firm, pungent and the backbone of most Indian street food dishes.",
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400",
    tags: ["onion", "vegetables", "fresh", "nashik"],
    minOrderQuantity: 10,
    maxOrderQuantity: 500,
    shelfLife: "2 weeks",
    origin: "Maharashtra",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Tomatoes (Hybrid Desi)",
    category: "Vegetables",
    price: 35,
    unit: "kg",
    stock: 600,
    description: "Plump, juicy hybrid tomatoes with balanced sweetness and acidity. Essential for gravies and chutneys.",
    image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400",
    tags: ["tomato", "vegetables", "fresh", "gravy"],
    minOrderQuantity: 10,
    maxOrderQuantity: 300,
    shelfLife: "1 week",
    origin: "Karnataka",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Potatoes (Jyoti Variety)",
    category: "Vegetables",
    price: 22,
    unit: "kg",
    stock: 1000,
    description: "Firm, starchy Jyoti potatoes from Agra. Ideal for aloo tikki, samosa filling, puri sabzi and vada pav.",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    tags: ["potato", "aloo", "vegetables", "tikki", "samosa"],
    minOrderQuantity: 10,
    maxOrderQuantity: 500,
    shelfLife: "3 weeks",
    origin: "Uttar Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Green Chillies (Long Variety)",
    category: "Vegetables",
    price: 80,
    unit: "kg",
    stock: 200,
    description: "Slim long green chillies with medium-high heat. Sliced for garnish, fried for snacks and ground for chutneys.",
    image: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400",
    tags: ["chilli", "green", "vegetables", "hot", "garnish"],
    minOrderQuantity: 2,
    maxOrderQuantity: 50,
    shelfLife: "1 week",
    origin: "Andhra Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Fresh Ginger Root",
    category: "Vegetables",
    price: 120,
    unit: "kg",
    stock: 150,
    description: "Fresh young ginger root — pungent, fibrous and aromatic. Ground for ginger paste or sliced for chai.",
    image: "https://images.unsplash.com/photo-1599940778173-e276d4acb2bb?w=400",
    tags: ["ginger", "adrak", "vegetables", "spice", "fresh"],
    minOrderQuantity: 2,
    maxOrderQuantity: 50,
    shelfLife: "2 weeks",
    origin: "Kerala",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Fresh Garlic (Indian)",
    category: "Vegetables",
    price: 140,
    unit: "kg",
    stock: 180,
    description: "Pungent Indian garlic with smaller cloves and stronger flavour. For pastes, pickles and tadka.",
    image: "https://images.unsplash.com/photo-1501420213590-9bc6db0d5fe0?w=400",
    tags: ["garlic", "lahsun", "vegetables", "spice", "fresh"],
    minOrderQuantity: 2,
    maxOrderQuantity: 50,
    shelfLife: "3 weeks",
    origin: "Madhya Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Fresh Coriander Leaves",
    category: "Vegetables",
    price: 60,
    unit: "kg",
    stock: 100,
    description: "Aromatic fresh coriander (dhania) harvested daily — used for garnishing, chutneys and salads.",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400",
    tags: ["coriander", "dhania", "herbs", "garnish", "fresh"],
    minOrderQuantity: 2,
    maxOrderQuantity: 30,
    shelfLife: "4 days",
    origin: "Haryana",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Lemon / Nimbu (Kagzi)",
    category: "Vegetables",
    price: 70,
    unit: "kg",
    stock: 200,
    description: "Thin-skinned Kagzi nimbu (paper lemon) bursting with juice. Essential for chaat, sherbet and marinades.",
    image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=400",
    tags: ["lemon", "nimbu", "citrus", "chaat", "fresh"],
    minOrderQuantity: 5,
    maxOrderQuantity: 100,
    shelfLife: "2 weeks",
    origin: "Andhra Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },

  // ── SWEETENERS & CONDIMENTS ───────────────────────────
  {
    name: "Jaggery (Kolhapuri Gur)",
    category: "Sweeteners",
    price: 85,
    unit: "kg",
    stock: 300,
    description: "Unrefined sugarcane jaggery from Kolhapur — earthy, rich and perfect for puran poli, til ladoo and dal.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    tags: ["jaggery", "gur", "sweetener", "unrefined", "natural"],
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    shelfLife: "6 months",
    origin: "Maharashtra",
    certifications: ["FSSAI", "Organic"],
    isActive: true,
  },
  {
    name: "Tamarind Pulp (Imli)",
    category: "Condiments",
    price: 110,
    unit: "kg",
    stock: 180,
    description: "Seedless tamarind pulp block from Andhra Pradesh — tangy base for imli chutney, sambar and rasam.",
    image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=400",
    tags: ["tamarind", "imli", "condiment", "chutney", "sour"],
    minOrderQuantity: 2,
    maxOrderQuantity: 50,
    shelfLife: "12 months",
    origin: "Andhra Pradesh",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "White Sugar (Refined)",
    category: "Sweeteners",
    price: 45,
    unit: "kg",
    stock: 500,
    description: "S-30 grade refined white cane sugar — fine crystals for daily use in tea, halwa and sweet dishes.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    tags: ["sugar", "sweetener", "refined", "cane"],
    minOrderQuantity: 10,
    maxOrderQuantity: 500,
    shelfLife: "24 months",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Dry Red Chillies (Byadgi)",
    category: "Spices",
    price: 260,
    unit: "kg",
    stock: 100,
    description: "Dark Byadgi dried chillies with deep colour and mild heat. Used for tempering and South Indian gravies.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    tags: ["chilli", "dry", "byadgi", "red", "whole"],
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    shelfLife: "12 months",
    origin: "Karnataka",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Mustard Seeds (Black Rai)",
    category: "Spices",
    price: 130,
    unit: "kg",
    stock: 160,
    description: "Small black mustard seeds for tempering in South Indian dishes, pickles and Bengali cuisine.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    tags: ["mustard", "rai", "seeds", "tempering", "tadka"],
    minOrderQuantity: 2,
    maxOrderQuantity: 50,
    shelfLife: "24 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Fenugreek Seeds (Methi Dana)",
    category: "Spices",
    price: 150,
    unit: "kg",
    stock: 120,
    description: "Slightly bitter fenugreek seeds used in pickles, methi sabzi, kadhi and as digestive aid.",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400",
    tags: ["fenugreek", "methi", "seeds", "bitter", "spice"],
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    shelfLife: "18 months",
    origin: "Gujarat",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Sesame Seeds (White Til)",
    category: "Spices",
    price: 200,
    unit: "kg",
    stock: 130,
    description: "Hulled white sesame seeds for till ladoo, til chikki, tahini and sprinkling on breads.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    tags: ["sesame", "til", "seeds", "ladoo", "chikki"],
    minOrderQuantity: 2,
    maxOrderQuantity: 40,
    shelfLife: "12 months",
    origin: "Gujarat",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Curry Leaves (Fresh)",
    category: "Vegetables",
    price: 90,
    unit: "kg",
    stock: 80,
    description: "Fresh curry leaves harvested from curry leaf trees in Tamil Nadu. Aromatic and essential for South Indian tempering.",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400",
    tags: ["curry-leaves", "kadi-patta", "herbs", "south-indian", "fresh"],
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
    shelfLife: "5 days",
    origin: "Tamil Nadu",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Dried Coconut (Copra)",
    category: "Condiments",
    price: 180,
    unit: "kg",
    stock: 150,
    description: "Dried mature coconut (copra) grated or sliced for chutneys, curries and coconut milk extraction.",
    image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=400",
    tags: ["coconut", "copra", "dried", "chutney", "south-indian"],
    minOrderQuantity: 2,
    maxOrderQuantity: 40,
    shelfLife: "6 months",
    origin: "Kerala",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Cashew Nuts (W240)",
    category: "Dry Fruits",
    price: 750,
    unit: "kg",
    stock: 60,
    description: "W240 grade whole cashews from Goa — creamy, large and ideal for gravies, kheer and mithai.",
    image: "https://images.unsplash.com/photo-1563208723-6ebea9049164?w=400",
    tags: ["cashew", "kaju", "dry-fruits", "nut", "premium"],
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
    shelfLife: "6 months",
    origin: "Goa",
    certifications: ["FSSAI", "Export Quality"],
    isActive: true,
  },
  {
    name: "Raisins (Kishmish)",
    category: "Dry Fruits",
    price: 380,
    unit: "kg",
    stock: 90,
    description: "Plump golden raisins from Sangli — sweet and used in pulao, halwa, mithai and trail mix.",
    image: "https://images.unsplash.com/photo-1563208723-6ebea9049164?w=400",
    tags: ["raisins", "kishmish", "dry-fruits", "sweet"],
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
    shelfLife: "12 months",
    origin: "Maharashtra",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Peanuts / Moongphali (Raw)",
    category: "Dry Fruits",
    price: 110,
    unit: "kg",
    stock: 300,
    description: "Raw shelled groundnuts from Gujarat. Roasted for chaat, boiled for snacks or ground for chutney.",
    image: "https://images.unsplash.com/photo-1563208723-6ebea9049164?w=400",
    tags: ["peanut", "moongphali", "groundnut", "raw", "chaat"],
    minOrderQuantity: 5,
    maxOrderQuantity: 100,
    shelfLife: "6 months",
    origin: "Gujarat",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Sev (Fine Fried Noodles)",
    category: "Ready Mix",
    price: 150,
    unit: "kg",
    stock: 200,
    description: "Crispy besan sev fried in sunflower oil — essential topping for bhel puri, sev puri and chaat.",
    image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=400",
    tags: ["sev", "chaat", "crispy", "bhel", "topping"],
    minOrderQuantity: 5,
    maxOrderQuantity: 50,
    shelfLife: "3 months",
    origin: "Maharashtra",
    certifications: ["FSSAI"],
    isActive: true,
  },
  {
    name: "Papad (Urad Dal Thin)",
    category: "Ready Mix",
    price: 200,
    unit: "kg",
    stock: 150,
    description: "Thin urad dal papads that can be roasted or fried in seconds. Served with meals or as a street snack.",
    image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=400",
    tags: ["papad", "urad-dal", "crispy", "snack"],
    minOrderQuantity: 2,
    maxOrderQuantity: 30,
    shelfLife: "6 months",
    origin: "Rajasthan",
    certifications: ["FSSAI"],
    isActive: true,
  },
];

export async function seedDemoData() {
  const userCount = await User.countDocuments();
  if (userCount > 0) {
    console.log("ℹ️  Skipping seed (database already has data).");
    return;
  }

  console.log("🌱 Seeding demo data...");

  const vendor = await User.create(DEMO_VENDOR);
  const vendor2 = await User.create(DEMO_VENDOR_2);
  const supplier = await User.create(DEMO_SUPPLIER);
  const supplier2 = await User.create(DEMO_SUPPLIER_2);

  // Split materials: first 30 items go to primary supplier, rest to secondary supplier
  const split = Math.ceil(DEMO_MATERIALS.length * 0.65);
  const mats1 = DEMO_MATERIALS.slice(0, split).map(m => ({ ...m, supplier: supplier._id }));
  const mats2 = DEMO_MATERIALS.slice(split).map(m => ({ ...m, supplier: supplier2._id }));

  await Material.insertMany([...mats1, ...mats2]);

  console.log("✅ Demo data seeded:");
  console.log(`   • Vendor:    ${vendor.email}   (password: vendor123)`);
  console.log(`   • Vendor 2:  ${vendor2.email} (password: vendor123)`);
  console.log(`   • Supplier:  ${supplier.email} (password: supplier123)`);
  console.log(`   • Supplier 2:${supplier2.email} (password: supplier123)`);
  console.log(`   • ${DEMO_MATERIALS.length} demo materials across 2 suppliers`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { connectDB, disconnectDB } = await import("../config/db.js");
  await connectDB();
  await seedDemoData();
  await disconnectDB();
  process.exit(0);
}
